change_cols_names_by_df = {"france": {"health": "severity_illness", "status": "treatment",
                                      "released_date": "recovery_date", "infection_reason": "infection_place"},

                           "tunisia": {"case": "id",
                                       "confirmation_date": "confirmed_date",
                                       "gender": "sex",
                                       "return_from": "infection_place",
                                       "symptomatic": "date_onset_symptoms"},

                           "japan": {"No.": "id", "Fixed date": "confirmed_date",
                                     "Age": "age_band", "residence": "region",
                                     "Surrounding patients *": "infected_by"},

                           "indonesia": {"patient_id": "id", "gender": "sex", "province": "region",
                                          "contacted_with": "infected_by",
                                         "status": "severity_illness_1", "health": "severity_illness_2",
                                         "infection_reason": "infection_place",
                                         "released_date": "recovery_date"},

                           "korea": {"patient_id": "id",
                                     "disease": "more_data_and_background_diseases_binary",
                                     "state": "severity_illness", "province": "region",
                                     "infection_case": "infection_place",
                                     "symptom_onset_date": "date_onset_symptoms",
                                     "age": "age_band",
                                     "released_date": "recovery_date",},

                           "world": {"ID": "id", "province": "region",
                                     "date_confirmation": "confirmed_date",
                                     "chronic_disease_binary": "more_data_and_background_diseases_binary",
                                     "chronic_disease": "background_diseases_origin",
                                     "outcome": "origin_severity_illness",
                                     "travel_history_location": "infection_place",
                                     'travel_history_dates': "return_date",
                                     "symptoms": "symptoms_origin"},

                           "new_zealand": {"MOH Case Number": "id", 'Location': 'city', 'Age Band': "age_band",
                                           'Gender': "sex",
                                           "Detection Date": "confirmed_date",
                                           'Arrival Date': "return_date",
                                           'Origin of Travel (Country)': "infection_place",
                                           "Origin of Travel (City)": "infection_place_city",
                                           "Travel Destination in NZ": "infection_place_local_1",
                                           "Cities visited in Transit": "infection_place_local_2",},

                           "guatemala": {'department': 'region',
                                         'illness': "background_diseases_origin",
                                         'arrival_date': "return_date",
                                         'infection_cause': "infection_place",
                                         'symptom_start_date': "date_onset_symptoms",
                                         'confirmation_date': 'confirmed_date',
                                         'recovery_date': 'recovery_date'},

                           "singapore": {"case": "id", 'date': 'confirmed_date', 'gender': "sex",
                                         'hospital': "name_of_hospital", 'imported': 'infection_place',
                                         'link': "infected_by", 'date discharged': 'recovery_date'},

                           "philippines": {'Sex': "sex", 'Age': 'age',
                                          'Residence in the Philippines': 'city',
                                          "Travel History": "infection_place_1",
                                          "History of Travel / Exposure": "infection_place_2",
                                          'Epi_Link': "infected_by",
                                          "Date of Onset of Symptoms": "date_onset_symptoms",
                                          'travel_history_dates': "return_date",
                                          "Date of Lab Confirmation": 'confirmed_date',
                                          "Admission / Consultation": "name_of_hospital",
                                          'Date of Admission': "date_admission_hospital",
                                          "Symptoms": "symptoms_origin_1",
                                          "Final Diagnosis": "symptoms_origin_2",
                                          'Other disease': "background_diseases_origin",
                                          'Health Status': "severity_illness",
                                          "Date of Final Status (recovered/expired)": 'date_death_or_discharge'},

                           "india_data": {"detected_city": 'city', 'detected_state': 'region',
                                          'diagnosed_date': 'confirmed_date',
                                          'gender': "sex", 'current_status': "severity_illness",
                                          "notes": 'infection_place', 'contacts': "infected_by",
                                          'status_change_date': 'date_death_or_discharge',
                                          'deceased': 'deceased_date'},

                           "india_wiki": {'Patient Number': 'id',
                                          'Date Confirmed': 'confirmed_date',
                                          'Status': "severity_illness", 'gender': "sex",
                                          'current_status': "severity_illness",
                                          'Contact With': "infected_by",
                                          'Outcome Date': 'date_death_or_discharge',
                                          "Patient Location": 'city', 'Sex': "sex", 'Age': 'age',
                                          'Comments': "type_relationship_with_infected person"},

                           "canada": {"case_id": "id", 'province': 'region', 'date_report': 'confirmed_date',
                                      'travel_history_country': "infection_place_1",
                                      'current_status': "severity_illness",
                                      'locally_acquired': "infection_place_2",
                                      "Patient Location": "city", 'Sex': "sex",
                                      'Age': 'age_band', 'Comments': "link_sicks"},

                           "vietnam": {"ID": "id", "Gender": "sex", 'Age': "age",
                                       'Detection Location': "region",
                                       "Hospital": "name_of_hospital",
                                       'Confirmed Date': "confirmed_date",
                                       'Travel Country, Correct': "infection_place_1",
                                       'Travel Country': "infection_place_2",
                                       "Source of Infection": "infected_by",
                                       'Detail Symptoms When Confirmed (clean up)': "symptoms_origin_1",
                                       'Health Condition When Confirmed': "symptoms_origin_2",
                                       'Developing Symptoms': "symptoms_origin_3",
                                       'Flight ID (Date)': "return_date",
                                       'Underlying Health Condition': "background_diseases_origin",
                                       'Discharged Date': "recovery_date",
                                       'Critical/severe condition': "severity_illness",
                                       "Relationship": "type_relationship_with_infected person",
                                       "Re-Infected": "re_infected_confirmed_date",
                                       "Re-discharged": "re_recovery_date"},

                           "mexico": {'SEXO': "sex", 'EDAD': "age",
                                      'TIPO_PACIENTE': "treatment",
                                      'FECHA_INGRESO': "confirmed_date",
                                      'FECHA_SINTOMAS': "date_onset_symptoms",
                                      'FECHA_DEF': "deceased_date",
                                      'DIABETES': " diabetes,",
                                      'EPOC': " chronic obstructive pulmonary,",
                                      'ASMA': " asthma,", 'INMUSUPR': " immunosuppression,",
                                      'HIPERTENSION': " hypertension,",
                                      'CARDIOVASCULAR': " cardiovascular,",
                                      'OBESIDAD': " obesity,",
                                      'RENAL_CRONICA': " kidney failure,",
                                      "NEUMONIA": "pneumonia,",
                                      "INTUBADO": "treatment_ever_intubated",
                                      "TABAQUISMO": "smoking",
                                      "UCI": "treatment_ever_icu"},

                           "colombia": {'ID DE CASO': "id",
                                        'SEXO': "sex", 'EDAD': "age",
                                        'NOMBRE DEPARTAMENTO':"region",
                                        'NOMBRE MUNICIPIO': "city",
                                        'UBICACION DEL CASO':"treatment_origin",
                                        "ESTADO":"severity_illness",
                                        'TIPO DE CONTAGIO': "infection_place",
                                        "TIPO DE RECUPERACION": "recovery_test"},

                           "kerla": {"Patient Number": "id",'Gender': "sex", 'Age Bracket': "age",
                                     "Origin Country": "country",
                                     'Notes': "infection_place_1",
                                     'Transmission Type': "infection_place_2",
                                     'Related Patients': "infected_by",
                                     'Date Announced': "confirmed_date",
                                     'Released': "recovery_date",
                                     'Deceased': "deceased_date",
                                     'Status': "severity_illness",
                                     'Residence City, District': "city"},

                           "hong_kong": {"Case_no_":"id", 'Gender': "sex", 'Age':"age",
                                         'Date_of_onset': "date_onset_symptoms",
                                         'Hospitalised_Discharged_Decease': "severity_illness",
                                         'Date_of_laboratory_confirmation': "confirmed_date",
                                         'District': "region"},

                           "toronto": {"_id":"id", 'Client Gender': "sex", "Age Group": "age_band",
                                       'Episode Date': "date_onset_symptoms",
                                       "Source of Infection": "infection_place",
                                       "Currently Hospitalized": "treatment_current_hospitalized",
                                       "Currently in ICU": "treatment_current_icu",
                                        "Currently Intubated": "treatment_current_intubated",
                                       'Outcome': "severity_illness",
                                       "Ever Hospitalized": "treatment_ever_hospitalized",
                                       "Ever in ICU": "treatment_ever_icu",
                                        "Ever Intubated": "treatment_ever_intubated"},

                           "usa": {"onset_dt": "date_onset_symptoms",
                                   'age_group': "age_band",
                                   "medcond_yn": "background_diseases_binary",
                                   "hosp_yn": "treatment_ever_hospitalized",
                                   "icu_yn": "treatment_ever_icu",
                                   "death_yn": "deceased"}}

drop_cols_by_df = {"france": ['group',  'infection_order',
                              'contact_number', 'source', 'comments'],
                   "japan": ["Close contact situation"],
                   "new_zealand": ['MOH Case Number', "Contraction in NZ",
                                   'Outside of Infection Period',
                                   'Flight Numbers'],
                   "guatemala": ['birth_date', 'group', 'source'],
                   "singapore": ['nationality', 'cluster_local'],
                   "philippines": ['Nationality',
                                 'Date of Announcement to the Public',
                                 "Status", 'Latitude', 'Longitude',
                                 'Residence Lat', 'Residence Long','Age Group',
                                 'Location'],
                   "india_data": ["id",'government_id','nationality',
                                'detected_district', 'current_location',
                                'current_location_pt', 'detected_city_pt'],
                   "india_wiki": ['Origin Location'],
                   "canada": ['case_id', 'provincial_case_id',
                            'health_region', 'report_week', 'travel_yn',
                            'case_source', 'additional_source', 'method_note',
                            "additional_info"],
                   "vietnam": ['Nationality', 'Treatment Location',

                             'Detail Symptoms When Confirmed', 'Travel History',
                             'Reference 1', 'Reference 2',
                             'Reference 3', 'Reference 4', 'Reference 5',
                             'Infection Cluster'],
                   "mexico": ['Unnamed: 0', 'SECTOR', 'ENTIDAD_UM',
                              'NACIONALIDAD', 'ENTIDAD_RES'],
                   "colombia":  ['FECHA REPORTE WEB', 'FECHA DE NOTIFICACION',
                               'CODIGO DIVIPOLA DEPARTAMENTO',
                               'CODIGO DIVIPOLA MUNICIPIO',
                               'FECHA REPORTE WEB DIA', 'FECHA REPORTE WEB MES',
                               'FECHA REPORTE WEB ANIO',
                               'FECHA REPORTE WEB NOMBRE MES',
                               'FECHA REPORTE WEB DIA SEMANA',
                               'FECHA DE NOTIFICACION DIA',
                               'FECHA DE NOTIFICACION MES',
                               'FECHA DE NOTIFICACION ANIO',
                               'FECHA DE NOTIFICACION NOMBRE MES',
                               'FECHA DE NOTIFICACION DIA SEMANA',
                               'FECHA DE INICIO DE SINTOMAS DIA',
                               'FECHA DE INICIO DE SINTOMAS DIA SEMANA',
                               'FECHA DE MUERTE DIA','PERTENENCIA ETNICA',
                               'NOMBRE DEL GRUPO ETNICO',
                               'FECHA DE MUERTE MES', 'FECHA DE MUERTE ANIO',
                               'FECHA DE MUERTE NOMBRE MES',
                               'FECHA DE INICIO DE SINTOMAS MES',
                               'FECHA DE INICIO DE SINTOMAS ANIO',
                               'FECHA DE INICIO DE SINTOMAS NOMBRE MES',
                               'FECHA DE MUERTE DIA SEMANA',
                               'FECHA DE DIAGNOSTICO DIA',
                               'FECHA DE DIAGNOSTICO MES',
                               'FECHA DE DIAGNOSTICO ANIO',
                               'FECHA DE DIAGNOSTICO NOMBRE MES',
                               'FECHA DE DIAGNOSTICO DIA SEMANA',
                               'FECHA DE RECUPERACION DIA',
                               'FECHA DE RECUPERACION MES',
                               'FECHA DE RECUPERACION ANIO',
                               'FECHA DE RECUPERACION NOMBRE MES',
                               'NOMBRE DEL GRUPO ETNICO',
                               'FECHA DE RECUPERACION DIA SEMANA'],
                   "world": ['latitude', 'longitude', 'geo_resolution',
                           'date_admission_hospital','lives_in_Wuhan',
                           'reported_market_exposure',
                           'additional_information','source', 'sequence_available',
                           'notes_for_discussion', 'location', 'admin3', 'admin2',
                           'admin1', 'country_new', 'admin_id',
                           'data_moderator_initials', 'travel_history_binary'],
                   "kerla": ['1', 'Unnamed: 3', 'Date Added', 'Detected City',
                           'Detected District',
                           'Known Cluster', 'DHS (Orig) Patient Number',
                           'Origin State', 'District Patient Number',
                           'City Patient Number','Recovery Time', 'Source(s)'],
                   "hong_kong": ['OBJECTID',  'GlobalID', "個案編號",
                               'Name_of_hospital_admitted', "發病日期", 'Confirmed',
                               "Shape__Area", 'Shape__Length', 'Status_Chi', '地區',
                               '性別', '年齡', '入住醫院名稱', '住院_出院_死亡',
                               '香港_非香港居民', '個案分類', '確定', 'Status',
                               'Case_classification', "實驗室確診報告日期",
                               'HK_Non_HK_resident'],
                 "toronto": [ 'Reported Date',
                              'Outbreak Associated','Neighbourhood Name',
                              'FSA', 'Classification'],
                 "usa": ['Race and ethnicity (combined)', 'cdc_report_dt']}
