import numpy as np

sex_dict = {"female": ["female", "Woman", "F", "Female", "Féminin", "f", "FEMALE", 2],
            "male": ["male", "Man", "M", "male\xa0?", "Male", "m", "MALE", "Masculin", 1],
            "transgender": ["TRANSGENDER"],
            np.nan: ["Checking", "investigating", "Not Reported", "x", "Unknown",
                     "Unspecified", "UNKNOWN", "OTHER", "Missing", "Other"]}


symptoms_bag_words = {"pneumonia": ["pneumonia", "pneumon"],
                      "hypertension": ['hypertens'],
                      "fever": ["fever", 'febr', 'feverish'],
                      "cough": ["cough", 'dcough', 'toss', 'couh'],
                      "fatigue": ["fatigu", 'fatigur', 'tired', 'lethargi', 'tire'],
                      "discomfort": ["discomfort", 'unwel'],
                      "weakness": ["weak", 'slump', 'somnol', "asthenia"],
                      "dizziness": ["dizzi"],
                      "rhinorrhoea": ["rhinorrhoea", 'rhinorrhea', 'cold'],
                      "sneezing": ["sneez"],
                      "sputum": ["sputum", "expector", 'phlegm', 'mucus'],
                      "headache": ["headach"],
                      "backache": ['backach'],
                      "diarrhea": ["diarrhea", 'diarrhoea'],
                      "chills": ["chill"],
                      "breathing difficulty": ["dyspnea", "dsypnea"],
                      "rigor": ["rigor"],
                      "pharyngalgia": ["pharyngalgia", 'pharyng', 'pharynx'],
                      "no_symptom": ["asymptomat", 'oligosymptomat', 'asymptomatic?'],
                      "nausea": ["nausea"],
                      "myalgia": ["malais", "myalgia", 'milagia', 'mialgia'],
                      'anorexia': ['anorexia', 'inapat', 'inappet'],
                      "conjunctivitis": ['conjunct'],
                      "toothache": ['toothach'],
                      "vomiting": ['vomit', 'emesi'],
                      "sweating": ['sweat'],
                      "wheezing": ['wheez'],
                      'gasp': ['gasp'],
                      "dysphagia": ['dysphagia'],
                      "sepsis": ['sepsi'],
                      "gastritis": ['gastriti'],
                      "hypoxia": ['hypoxia'],
                      "cardiac arrhythmia": ['arrhythmia'],
                      #                       "ECMO": ['ecmo'],
                      'azotemia': ['azotemia'],
                      'influenza': ['influenza'],
                      "rash": ["rash"],
                      "atherosclerosis": ["atherosclerot", 'atherosclerosi'],
                      "diabetes": ["diabeti"],
                      "heart failure": ['cardiaco']}

symptoms_sentences_bag = {"fever": ['flu', 'like'],
                          "nasal congestion": ['nasal', 'congest', 'discharg', 'flu', 'like'],
                          "pleural effusion": ['pleural', 'effus'],
                          "sore throat": ['sore', "throat", 'flu', 'like', 'throath', 'throa'],
                          "pleuritic chest pain": ['pleurit', 'chest', 'pain', 'pressur'],
                          "chest distress": ['chest', 'distress', 'tight'],
                          "muscular stiffness": ['muscular', 'stiff'],
                          "myalgia": ['general', 'muscular', "sore", 'ach', 'muscl', "pain", 'bodi', 'limb', 'flu',
                                      'like'],
                          "secondary infection": [ "syndrom", "secondari"],
                          "joint pain": ['stiff', 'joint', 'pain'],
                          "rhinorrhoea": ['runni', 'nose', 'run'],
                          "stuffy nose": ['stuffi', 'nose'],
                          "bleeding nose": ['bleed', 'nose'],
                          "weakness": ['lack', 'energi', 'flu', 'like'],
                          "heart failure": ['heart', 'failur', ],
                          "breathing difficulty": ['difficulti', 'breath', 'short', 'difficuti', 'distress',
                                                   'respiratori',
                                                   'troubl', 'problem', 'sintoma', 'respirat', 'symptom', 'complaint'],
                          "esophageal reflux": ['esophag', 'reflux'],
                          "abdominal pain": ['abdomin', 'pain'],
                          "respiratory infection": ['pulmonari', 'inflamm', 'respiratori', 'infect', '(arvi)',
                                                    'diseas'],
                          "bone pain": ['bone', 'pain'],
                          "kidney failure": ['kidney', 'failur', 'renal', 'injuri'],
                          "aggressive pulmonary": ['aggress', 'pulmonari'],
                          "no_symptom": ['no', 'symptom'],
                          "eye irritation": ['eye', 'irrit'],
                          "lesions on chest": ['lesion', 'chest'],
                          "dry mouth": ['dri', 'mouth'],
                          "dry throat": ['dri', 'throat'],
                          "acute coronary syndrome": ['acut', 'coronari'],
                          "cardiac arrhythmia": ['cardiac', 'arrhythmia', 'dysrhythmia'],
                          "septic shock": ['septic', 'shock', 'schock'],
                          "cardiogenic shock": ['cardiogen', 'shock'],
                          "heart attack": ['myocardi', 'infarct', 'myocordi'],
                          "electrolyte disorders": ['multipl', 'electrolyt', 'imbal'],
                          "organ failure": ['multipl', 'organ', 'failur'],
                          "primary myelofibrosis": ['primari', 'myelofibrosi'],
                          "myocardial dysfunction": ['myocardi', 'dysfunct'],
                          "cardiac arrest": ['cardiopulmonari', 'arrest', 'cardiac', 'arrest'],
                          "respiratory failure": ['respiratori', 'failur'],
                          "difficulty walking": ['difficulti', 'walk'],
                          #                           "oxygen mask": ['oxygen', 'mask', "oxi"],
                          #                           "dialysis" : ['dialysi'],
                          #                           "mechanical ventilation":['mechan', 'ventil'],
                          "gastrointestinal bleeding": ['gastrointestin', 'bleed']}

background_diseases_bag_words = {"hypertension": ["hypertens", 'hypertenst'],
                                 "tuberculosis": ['tuberculosi'],
                                 'myeloma': ['myeloma'],
                                 'pneumonia': ['pneumonia'],
                                 "diabetes": ['diabet', "mellitus"],
                                 "tuberculosis": ["tuberculosi"],
                                 "atherosclerosis": ['atherosclerosi'],
                                 "parkinson": ["parkinso", "madopar", 'parkinson'],
                                 "stenocardia": ['stenocardia'],
                                 "hypertriglyceridemia": ['hypertriglyceridemia', ],
                                 "hypothyroidism": ['hypothyroid'],
                                 "obesity": ['obes', ],
                                 "dyslipidemia": ['dyslipidemia', 'dislipidemia'],
                                 "chronic obstructive pulmonary": ['copd', ],
                                 "cardiomyopathy": ['cardiomyopathi'],
                                 "hiv": ["hiv", ],
                                 "asthma": ["asthma", ],
                                 "azotemia": ["azotemia"],
                                 "encephalomalacia": ['encephalomalacia'],
                                 "on dialysis": ["dialysi"],
                                 "cardiovascular": ["cardiovascular", 'cardiac'],
                                 "frequent ventricular premature beat": ["fvpb"],
                                 "stent  implanted": ['stent'],
                                 'thalassemia': ['thalassemia'],
                                 "gastritis": ['gastriti'],
                                 "leukemia": ['leukemia'],
                                 "cancer": ["cancer"],
                                 "POTS": ['pot']}

background_diseases_sentences_bag = {"hypertension": ['high', 'blood', 'pressur'],
                                     "prostate cancer": ['prostat', 'cancer'],
                                     "colon cancer": ['colon', 'cancer'],
                                     "coronary heart disease": ['coronari', 'heart', 'arteri', 'ischem', 'cardiopatía'],
                                     "coronary heart disease": ['coronari', 'heart', 'arteri', 'ischem', 'cardiopatía'],
                                     "coronary bypass surgery": ['bypass', 'surgeri'],
                                     "lung cancer": ['lung', 'cancer'],
                                     "tongue cancer": ['tongu', 'cancer'],
                                     "valvular heart disease": ['valvular', 'heart'],
                                     "renal transplant": ['renal', 'transplant'],
                                     "systemic arterial hypertension": ['system', 'hypertens'],
                                     "atrial fibrillation": ['atrial', 'fibril'],
                                     "kidney failure": ['renal', "insuffici", 'kidney', 'injuri'],
                                     "chronic kidney disease": ['chronic', 'renal', 'kidney', 'dz', 'diseas'],
                                     "impaired fasting glucose": ['impair', 'fast', 'glucos'],
                                     "gastrointestinal bleeding": ['git', 'bleed', 'hemorrhag', 'digest', "tra"],
                                     "arrhythmia": ['cardiac', 'dysrhythmia'],
                                     "benign prostatic hyperplasia": ['benign', 'prostat'],
                                     "chronic obstructive pulmonary disease": ['obstruct', 'pulmonari',
                                                                               'condit', 'chronic', 'bronchiti',
                                                                               'cronic'],
                                     "prostate hypertrophy": ['prostat', 'hypertrophi'],
                                     "diabetic nephropathy": ['diabet', 'nephropathi'],
                                     "hip replacement": ['hip', "replac"],
                                     "cerebral infarction": ['hypertens', 'cerebr', 'infarct'],
                                     "hepatitis B": ["hepat", 'b'],
                                     "frequent ventricular premature beat": ["frequent", 'ventricular', 'prematur',
                                                                             'beat'],
                                     "endocrine condition": ['endocrin', 'condit'],
                                     "hypertensive nephrosclerosis": ['hypertens', 'nephrosclerosi'],
                                     "peripheral arterial occlusive disease": ['arteri', 'occlus'],
                                     "vestibular disorders": ['vestibular', 'disord'],
                                     "brain haemorrhage": ['brain', 'haemorrhag'],
                                     "dilated cardiomyopathy": ["dilat", "cardiomyopathi"],
                                     "prostat cancer": ["prostat", "cancer"]}


symptoms_to_background_diseases_bag_words = {"diabetes": ['diabet', "mellitus"],
                                             "cardiomyopathy": ['cardiomyopathi'],
                                             "atherosclerotic": ['atherosclerot']}

symptoms_to_background_diseases_sentences_bag = {"chronic obstructive pulmonary disease": ['obstruct', 'pulmonari'],
                                                 "coronary heart disease": ['ischem', 'heart'],
                                                 "chronic kidney disease": ['chronic', 'kidney', 'diseas']}

mexico_background_diseases_cols = [" diabetes,",
                                   " chronic obstructive pulmonary,",
                                    " asthma,",  " immunosuppression,",
                                    " hypertension,",
                                    " cardiovascular,",
                                    " obesity,",
                                    " kidney failure,",
                                   "pneumonia,"]

world_treatment_bag_words = {"home isolation": ["home", "quarantin"],
             "clinic": [],
             "hospitalized": ['hospit', "follow-up", 'intub', "fever"],
             }

world_treatment_sentences_bag = {"home isolation": ['not', 'hospit'],
                 "clinic": [],
                 "hospitalized": ['from', 'hospit', 'intens', 'care', 'under', 'treatment'],
                 }

severity_illness_dict = {"asymptomatic": ["Asymptomatic", "Asintomático"],
            "good": ["good", "Leve", 'Moderado', "Mild", "In progress", "In progress", "isolated"],
            "critical": ["critical", "Grave", "Severe", "Critical"],
            "deceased": ["deceased", 2, "Fallecido", "Died", "Deceased", "FATAL"],
            "cured": ["cured", 1, "Discharged", "Recovered", "Cured", "released",
                      "Clinically Recovered", "RESOLVED"],
            np.nan: [0, "Nan", "health", "Hospitalized", "Under Treatment", "To be provided",
                     "Pending admission", "Hospitalised", "ACTIVE "]}

world_severity_illness_bag_words = {"asymptomatic":['asymptomat'],
            "good": ["good", "stabl", "follow", 'mild', "follow-up", 'moder'],
            "critical": ["critic", "intens", "sever", 'unstabl'],
            "deceased": ["death", "dead", "die", "deceas", 'fatal' ],
            "cured": ["discharg", "releas", "cure", "recov", 'health', 'resolv'],
            "": ["isol", 'valid',  'treatment', "For validation"]}

world_severity_illness_sentences_bag = {"good": ['not', 'hospit', 'in', 'progress'],
                "critical": ['intens', 'care'],
                "deceased": [],
                "cured": ["discharged", "hospit"]}


severity_illness_from_symptoms_by_WHO = {"good": ["pneumonia", 'fever', 'cough', 'fatigue',
                                                  'discomfort', 'weakness', 'dizziness',
                                                  'rhinorrhoea', 'sneezing', 'sputum', 'headache',
                                                  'backache', 'diarrhea', 'chills', 'nausea',
                                                  'myalgia',
                     'anorexia','toothache','vomiting','gasp','influenza','sweating ','rigor',
                     'conjunctivitis','pharyngalgia','gastritis','influenza', 'nasal congestion',
                     'sore throat','muscular stiffness','myalgia','joint pain','esophageal reflux',
                     'abdominal pain','bone pain','eye irritation','dry mouth','dry throat',
                     'gastrointestinal bleeding','stuffy nose',"difficulty walking", "pleuritic chest pain"],
     "asymptomatic": ["no_symptom"],
    'critical': ["server" , "breathing difficulty", "dysphagia", "hypoxia", "septic",
                 "cardiac arrhythmia",'organ failure', 'respiratory failure',  'breathing difficulty'
    "sepsis", "hypertension", "azotemia", "pleural effusion","heart failure","kidney failure",
    "chest distress","acute coronary syndrome","cardiac arrhythmia",'septic shock',
    'cardiogenic shock','heart attack','electrolyte disorders','organ failure','primary myelofibrosis',
    'myocardial dysfunction','cardiac arrest','lesions on chest','respiratory failure',"respiratory infection",'primary myelofibrosis']}

binary_dict = {0: ["No", 2],1: [1, "Yes"], np.nan: [97, 99, "Missing", "Unknown"]}