import numpy as np

change_cols_names_by_df = {"france": {"health": "severity_illness", "status": "treatment"},

                           "tunisia": {"case": "id",
                                       "confirmation_date": "confirmed_date",
                                       "gender": "sex",
                                       "return_from": "infection_place",
                                       "symptomatic": "date_onset_symptoms"},

                           "japan": {"No.": "id", "Fixed date": "confirmed_date",
                                     "Age": "age_band", "residence": "region",
                                     "Surrounding patients *": "infected_by"},

                           "indonesia": {"patient_id": "id", "gender": "sex", "province": "region",
                                         "hospital": "treatment", "contacted_with": "infected_by",
                                         "current_state": "severity_illness"},

                           "korea": {"patient_id": "id",
                                     "disease": "more_data_and_background_diseases_binary",
                                     "state": "severity_illness", "province": "region",
                                     "infection_case": "infection_place",
                                     "symptom_onset_date": "date_onset_symptoms",
                                     "age": "age_band"},

                           "world": {"province": "region",
                                     "date_confirmation": "confirmed_date",
                                     "chronic_disease_binary": "more_data_and_background_diseases_binary",
                                     "chronic_disease": "background_diseases_origin",
                                     "outcome": "origin_severity_illness",
                                     "travel_history_location": "infection_place",
                                     'travel_history_dates': "return_date",
                                     "symptoms": "symptoms_origin"},

                           "new_zealand": {'Location': 'city', 'Age Band': "age_band",
                                           'Gender': "sex",
                                           "Detection Date": "confirmed_date",
                                           'Arrival Date': "return_date",
                                           'Origin of Travel (Country)': "infection_place", },

                           "guatemala": {'department': 'region',
                                         'illness': "background_diseases_origin",
                                         'arrival_date': "return_date",
                                         'infection_cause': "infection_place",
                                         'symptom_start_date': "date_onset_symptoms",
                                         'confirmation_date': 'confirmed_date',
                                         'recovery_date': 'released_date'},

                           "singapore": {"case": "id", 'date': 'confirmed_date', 'gender': "sex",
                                         'hospital': "treatment", 'imported': 'infection_place',
                                         'link': "infected_by", 'date discharged': 'released_date'},

                           "philippines": {'Sex': "sex", 'Age': 'age',
                                          'Residence in the Philippines': 'city',
                                          "Travel History": "infection_place",
                                          'Epi_Link': "infected_by",
                                          "Date of Onset of Symptoms": "date_onset_symptoms",
                                          'travel_history_dates': "return_date",
                                          "Date of Lab Confirmation": 'confirmed_date',
                                          "Admission / Consultation": "treatment",
                                          'Date of Admission': "date_admission_hospital",
                                          "Symptoms": "symptoms_origin",
                                          'Other disease': "background_diseases_origin",
                                          'Health Status': "severity_illness",
                                          "Date of Final Status (recovered/expired)": 'date_death_or_discharge'},

                           "india_data": {"detected_city": 'city', 'detected_state': 'region',
                                          'diagnosed_date': 'confirmed_date',
                                          'gender': "sex", 'current_status': "severity_illness",
                                          "notes": 'infection_place', 'contacts': "link_sicks",
                                          'status_change_date': 'date_death_or_discharge',
                                          'deceased': 'deceased_date', 'link_sicks': "infected_by"},

                           "india_wiki": {'Patient Number': 'id',
                                          'Date Confirmed': 'confirmed_date',
                                          'Status': "severity_illness", 'gender': "sex",
                                          'current_status': "severity_illness",
                                          'Contact With': "infected_by",
                                          'Outcome Date': 'date_death_or_discharge',
                                          "Patient Location": 'city', 'Sex': "sex", 'Age': 'age',
                                          'Comments': "link_sicks"},

                           "canada": {'province': 'region', 'date_report': 'confirmed_date',
                                      'travel_history_country': "infection_place",
                                      'current_status': "severity_illness",
                                      'locally_acquired': "infection_cause",
                                      "Patient Location": "city", 'Sex': "sex",
                                      'Age': 'age_band', 'Comments': "link_sicks"},

                           "vietnam": {"ID": "id", "Gender": "sex", 'Age': "age",
                                       'Detection Location': "region", "Hospital": "treatment",
                                       'Confirmed Date': "confirmed_date",
                                       'Travel Country, Correct': "infection_place",
                                       "Source of Infection": "infected_by",
                                       'Detail Symptoms When Confirmed (clean up)': "symptoms_origin",
                                       'Flight ID (Date)': "return_date",
                                       'Underlying Health Condition': "background_diseases_origin", 'Discharged Date': "released_date",
                                       'Critical/severe condition': "severity_illness"},

                           "mexico": {'SEXO': "sex", 'EDAD': "age",
                                      'TIPO_PACIENTE': "treatment",
                                      'FECHA_INGRESO': "confirmed_date",
                                      'FECHA_SINTOMAS': "date_onset_symptoms",
                                      'FECHA_DEF': "deceased_date",
                                      'DIABETES': " diabetes,",
                                      'EPOC': " chronic obstructive pulmonary,",
                                      'ASMA': " asthma,", 'INMUSUPR': " immunosuppression,",
                                      'HIPERTENSION': " hypertension,",
                                      'CARDIOVASCULAR': " cardiovascular,",
                                      'OBESIDAD': " obesity,",
                                      'RENAL_CRONICA': " kidney failure,"},

                           "colombia": {"id": 'ID DE CASO',
                                        'SEXO': "sex", 'EDAD': "age",
                                        'NOMBRE DEPARTAMENTO':"region",
                                        'NOMBRE MUNICIPIO': "city",
                                        'UBICACION DEL CASO':"treatment_origin",
                                        "ESTADO":"severity_illness",
                                        'TIPO DE CONTAGIO': "infection_place",
                                        "TIPO DE RECUPERACION": "recovery_test"},

                           "kerla": {'Gender': "sex", 'Age Bracket': "age",
                                     "Origin Country": "country",
                                     'Notes': "infection_place",
                                     'Related Patients': "infected_by",
                                     'Date Announced': "confirmed_date",
                                     'Released': "released_date",
                                     'Deceased': "deceased_date",
                                     'Status': "severity_illness",
                                     'Residence City, District':"city"},

                           "hong_kong": {'Gender': "sex", 'Age':"age",
                                         'Date_of_onset': "date_onset_symptoms",
                                         'Hospitalised_Discharged_Decease': "severity_illness",
                                         'Date_of_laboratory_confirmation': "confirmed_date",
                                         'District': "region"},

                           "toronto": {'Client Gender': "sex", "Age Group": "age_band",
                                       'Episode Date': "date_onset_symptoms",
                                       'Outcome': "severity_illness",
                                       "treatment": "Ever Hospitalized"},

                           "usa": {"onset_dt": "date_onset_symptoms",
                                   'age_group': "age_band",
                                   "medcond_yn": "background_diseases_binary"}}

drop_cols_by_df = {"france": ['group', 'infection_reason', 'infection_order',
                              'contact_number', 'source', 'comments'],
                   "japan": ["Close contact situation"],
                   "new_zealand": ['MOH Case Number', "Contraction in NZ",
                                   'Outside of Infection Period',
                                   'Origin of Travel (City)',
                                   'Travel Destination in NZ',
                                   'Cities visited in Transit',
                                   'Flight Numbers'],
                   "guatemala": ['birth_date', 'group', 'source'],
                   "singapore": ['nationality', 'cluster_local'],
                   "philippines": ['Nationality',
                                 'Date of Announcement to the Public',
                                 "Status", 'Latitude', 'Longitude',
                                 'Residence Lat', 'Residence Long','Age Group',
                                 'Location'],
                   "india_data": ["id",'government_id','nationality',
                                'detected_district', 'current_location',
                                'current_location_pt', 'detected_city_pt'],
                   "india_wiki": ['Origin Location'],
                   "canada": ['case_id', 'provincial_case_id',
                            'health_region', 'report_week', 'travel_yn',
                            'case_source', 'additional_source', 'method_note',
                            "additional_info"],
                   "vietnam": ['Nationality', 'Treatment Location',
                             'Health Condition When Confirmed',
                             'Detail Symptoms When Confirmed', 'Travel History',
                             'Reference 1', 'Reference 2',
                             'Reference 3', 'Reference 4', 'Reference 5',
                             'Travel Country', 'Relationship', 'Infection Cluster'],
                   "mexico": ['Unnamed: 0', 'SECTOR', 'ENTIDAD_UM',
                              'NACIONALIDAD', 'ENTIDAD_RES'],
                   "colombia":  ['FECHA REPORTE WEB', 'FECHA DE NOTIFICACION',
                               'CODIGO DIVIPOLA DEPARTAMENTO',
                               'CODIGO DIVIPOLA MUNICIPIO',
                               'FECHA REPORTE WEB DIA', 'FECHA REPORTE WEB MES',
                               'FECHA REPORTE WEB ANIO',
                               'FECHA REPORTE WEB NOMBRE MES',
                               'FECHA REPORTE WEB DIA SEMANA',
                               'FECHA DE NOTIFICACION DIA',
                               'FECHA DE NOTIFICACION MES',
                               'FECHA DE NOTIFICACION ANIO',
                               'FECHA DE NOTIFICACION NOMBRE MES',
                               'FECHA DE NOTIFICACION DIA SEMANA',
                               'FECHA DE INICIO DE SINTOMAS DIA',
                               'FECHA DE INICIO DE SINTOMAS DIA SEMANA',
                               'FECHA DE MUERTE DIA','PERTENENCIA ETNICA',
                               'NOMBRE DEL GRUPO ETNICO',
                               'FECHA DE MUERTE MES', 'FECHA DE MUERTE ANIO',
                               'FECHA DE MUERTE NOMBRE MES',
                               'FECHA DE INICIO DE SINTOMAS MES',
                               'FECHA DE INICIO DE SINTOMAS ANIO',
                               'FECHA DE INICIO DE SINTOMAS NOMBRE MES',
                               'FECHA DE MUERTE DIA SEMANA',
                               'FECHA DE DIAGNOSTICO DIA',
                               'FECHA DE DIAGNOSTICO MES',
                               'FECHA DE DIAGNOSTICO ANIO',
                               'FECHA DE DIAGNOSTICO NOMBRE MES',
                               'FECHA DE DIAGNOSTICO DIA SEMANA',
                               'FECHA DE RECUPERACION DIA',
                               'FECHA DE RECUPERACION MES',
                               'FECHA DE RECUPERACION ANIO',
                               'FECHA DE RECUPERACION NOMBRE MES',
                               'NOMBRE DEL GRUPO ETNICO',
                               'FECHA DE RECUPERACION DIA SEMANA'],
                   "world": ['latitude', 'longitude', 'geo_resolution',
                           'date_admission_hospital','lives_in_Wuhan',
                           'infection_place', 'reported_market_exposure',
                           'additional_information','source', 'sequence_available',
                           'notes_for_discussion', 'location', 'admin3', 'admin2',
                           'admin1', 'country_new', 'admin_id',
                           'data_moderator_initials', 'travel_history_binary'],
                   "kerla": ['1', 'Unnamed: 3', 'Date Added', 'Detected City',
                           'Detected District', 'Transmission Type',
                           'Known Cluster', 'DHS (Orig) Patient Number',
                           'Origin State', 'District Patient Number',
                           'City Patient Number','Recovery Time', 'Source(s)'],
                   "hong_kong": ['OBJECTID',  'GlobalID','Case_no_', "個案編號",
                               'Name_of_hospital_admitted', "發病日期", 'Confirmed',
                               "Shape__Area", 'Shape__Length', 'Status_Chi', '地區',
                               '性別', '年齡', '入住醫院名稱', '住院_出院_死亡',
                               '香港_非香港居民', '個案分類', '確定', 'Status',
                               'Case_classification', "實驗室確診報告日期",
                               'HK_Non_HK_resident'],
                 "toronto": [ 'Currently Intubated', 'Currently in ICU',
                              'Currently Hospitalized','Reported Date','_id',
                              'Outbreak Associated','Neighbourhood Name',
                              'FSA','Source of Infection', 'Classification'],
                 "usa": ['Race and ethnicity (combined)', 'cdc_report_dt']}

sex_dict = {"female": ["female", "Woman", "F", "Female", "Féminin", "f", "FEMALE", 2],
            "male": ["male", "Man", "M", "male\xa0?", "Male", "m", "MALE", "Masculin", 1],
            "transgender": ["TRANSGENDER"],
            np.nan: ["Checking", "investigating", "Not Reported", "x", "Unknown",
                     "Unspecified", "UNKNOWN", "OTHER", "Missing", "Other"]}


symptoms_bag_words = {"pneumonia": ["pneumonia", "pneumon"],
                      "hypertension": ['hypertens'],
                      "fever": ["fever", 'febr', 'feverish'],
                      "cough": ["cough", 'dcough', 'toss', 'couh'],
                      "fatigue": ["fatigu", 'fatigur', 'tired', 'lethargi', 'tire'],
                      "discomfort": ["discomfort", 'unwel'],
                      "weakness": ["weak", 'slump', 'somnol', "asthenia"],
                      "dizziness": ["dizzi"],
                      "rhinorrhoea": ["rhinorrhoea", 'rhinorrhea', 'cold'],
                      "sneezing": ["sneez"],
                      "sputum": ["sputum", "expector", 'phlegm', 'mucus'],
                      "headache": ["headach"],
                      "backache": ['backach'],
                      "diarrhea": ["diarrhea", 'diarrhoea'],
                      "chills": ["chill"],
                      "breathing difficulty": ["dyspnea", "dsypnea"],
                      "rigor": ["rigor"],
                      "pharyngalgia": ["pharyngalgia", 'pharyng', 'pharynx'],
                      "no_symptom": ["asymptomat", 'oligosymptomat', 'asymptomatic?'],
                      "nausea": ["nausea"],
                      "myalgia": ["malais", "myalgia", 'milagia', 'mialgia'],
                      'anorexia': ['anorexia', 'inapat', 'inappet'],
                      "conjunctivitis": ['conjunct'],
                      "toothache": ['toothach'],
                      "vomiting": ['vomit', 'emesi'],
                      "sweating": ['sweat'],
                      "wheezing": ['wheez'],
                      'gasp': ['gasp'],
                      "dysphagia": ['dysphagia'],
                      "sepsis": ['sepsi'],
                      "gastritis": ['gastriti'],
                      "hypoxia": ['hypoxia'],
                      "cardiac arrhythmia": ['arrhythmia'],
                      #                       "ECMO": ['ecmo'],
                      'azotemia': ['azotemia'],
                      'influenza': ['influenza'],
                      "rash": ["rash"],
                      "atherosclerosis": ["atherosclerot", 'atherosclerosi'],
                      "diabetes": ["diabeti"],
                      "heart failure": ['cardiaco']}

symptoms_sentences_bag = {"fever": ['flu', 'like'],
                          "nasal congestion": ['nasal', 'congest', 'discharg', 'flu', 'like'],
                          "pleural effusion": ['pleural', 'effus'],
                          "sore throat": ['sore', "throat", 'flu', 'like', 'throath', 'throa'],
                          "pleuritic chest pain": ['pleurit', 'chest', 'pain', 'pressur'],
                          "chest distress": ['chest', 'distress', 'tight'],
                          "muscular stiffness": ['muscular', 'stiff'],
                          "myalgia": ['general', 'muscular', "sore", 'ach', 'muscl', "pain", 'bodi', 'limb', 'flu',
                                      'like'],
                          "secondary infection": [ "syndrom", "secondari"],
                          "joint pain": ['stiff', 'joint', 'pain'],
                          "rhinorrhoea": ['runni', 'nose', 'run'],
                          "stuffy nose": ['stuffi', 'nose'],
                          "bleeding nose": ['bleed', 'nose'],
                          "weakness": ['lack', 'energi', 'flu', 'like'],
                          "heart failure": ['heart', 'failur', ],
                          "breathing difficulty": ['difficulti', 'breath', 'short', 'difficuti', 'distress',
                                                   'respiratori',
                                                   'troubl', 'problem', 'sintoma', 'respirat', 'symptom', 'complaint'],
                          "esophageal reflux": ['esophag', 'reflux'],
                          "abdominal pain": ['abdomin', 'pain'],
                          "respiratory infection": ['pulmonari', 'inflamm', 'respiratori', 'infect', '(arvi)',
                                                    'diseas'],
                          "bone pain": ['bone', 'pain'],
                          "kidney failure": ['kidney', 'failur', 'renal', 'injuri'],
                          "aggressive pulmonary": ['aggress', 'pulmonari'],
                          "no_symptom": ['no', 'symptom'],
                          "eye irritation": ['eye', 'irrit'],
                          "lesions on chest": ['lesion', 'chest'],
                          "dry mouth": ['dri', 'mouth'],
                          "dry throat": ['dri', 'throat'],
                          "acute coronary syndrome": ['acut', 'coronari'],
                          "cardiac arrhythmia": ['cardiac', 'arrhythmia', 'dysrhythmia'],
                          "septic shock": ['septic', 'shock', 'schock'],
                          "cardiogenic shock": ['cardiogen', 'shock'],
                          "heart attack": ['myocardi', 'infarct', 'myocordi'],
                          "electrolyte disorders": ['multipl', 'electrolyt', 'imbal'],
                          "organ failure": ['multipl', 'organ', 'failur'],
                          "primary myelofibrosis": ['primari', 'myelofibrosi'],
                          "myocardial dysfunction": ['myocardi', 'dysfunct'],
                          "cardiac arrest": ['cardiopulmonari', 'arrest', 'cardiac', 'arrest'],
                          "respiratory failure": ['respiratori', 'failur'],
                          "difficulty walking": ['difficulti', 'walk'],
                          #                           "oxygen mask": ['oxygen', 'mask', "oxi"],
                          #                           "dialysis" : ['dialysi'],
                          #                           "mechanical ventilation":['mechan', 'ventil'],
                          "gastrointestinal bleeding": ['gastrointestin', 'bleed']}

background_diseases_bag_words = {"hypertension": ["hypertens", 'hypertenst'],
                                 "tuberculosis": ['tuberculosi'],
                                 'myeloma': ['myeloma'],
                                 'pneumonia': ['pneumonia'],
                                 "diabetes": ['diabet', "mellitus"],
                                 "tuberculosis": ["tuberculosi"],
                                 "atherosclerosis": ['atherosclerosi'],
                                 "parkinson": ["parkinso", "madopar", 'parkinson'],
                                 "stenocardia": ['stenocardia'],
                                 "hypertriglyceridemia": ['hypertriglyceridemia', ],
                                 "hypothyroidism": ['hypothyroid'],
                                 "obesity": ['obes', ],
                                 "dyslipidemia": ['dyslipidemia', 'dislipidemia'],
                                 "chronic obstructive pulmonary": ['copd', ],
                                 "cardiomyopathy": ['cardiomyopathi'],
                                 "hiv": ["hiv", ],
                                 "asthma": ["asthma", ],
                                 "azotemia": ["azotemia"],
                                 "encephalomalacia": ['encephalomalacia'],
                                 "on dialysis": ["dialysi"],
                                 "cardiovascular": ["cardiovascular", 'cardiac'],
                                 "frequent ventricular premature beat": ["fvpb"],
                                 "stent  implanted": ['stent'],
                                 'thalassemia': ['thalassemia'],
                                 "gastritis": ['gastriti'],
                                 "leukemia": ['leukemia'],
                                 "cancer": ["cancer"],
                                 "POTS": ['pot']}

background_diseases_sentences_bag = {"hypertension": ['high', 'blood', 'pressur'],
                                     "prostate cancer": ['prostat', 'cancer'],
                                     "colon cancer": ['colon', 'cancer'],
                                     "coronary heart disease": ['coronari', 'heart', 'arteri', 'ischem', 'cardiopatía'],
                                     "coronary heart disease": ['coronari', 'heart', 'arteri', 'ischem', 'cardiopatía'],
                                     "coronary bypass surgery": ['bypass', 'surgeri'],
                                     "lung cancer": ['lung', 'cancer'],
                                     "tongue cancer": ['tongu', 'cancer'],
                                     "valvular heart disease": ['valvular', 'heart'],
                                     "renal transplant": ['renal', 'transplant'],
                                     "systemic arterial hypertension": ['system', 'hypertens'],
                                     "atrial fibrillation": ['atrial', 'fibril'],
                                     "kidney failure": ['renal', "insuffici", 'kidney', 'injuri'],
                                     "chronic kidney disease": ['chronic', 'renal', 'kidney', 'dz', 'diseas'],
                                     "impaired fasting glucose": ['impair', 'fast', 'glucos'],
                                     "gastrointestinal bleeding": ['git', 'bleed', 'hemorrhag', 'digest', "tra"],
                                     "arrhythmia": ['cardiac', 'dysrhythmia'],
                                     "benign prostatic hyperplasia": ['benign', 'prostat'],
                                     "chronic obstructive pulmonary disease": ['obstruct', 'pulmonari',
                                                                               'condit', 'chronic', 'bronchiti',
                                                                               'cronic'],
                                     "prostate hypertrophy": ['prostat', 'hypertrophi'],
                                     "diabetic nephropathy": ['diabet', 'nephropathi'],
                                     "hip replacement": ['hip', "replac"],
                                     "cerebral infarction": ['hypertens', 'cerebr', 'infarct'],
                                     "hepatitis B": ["hepat", 'b'],
                                     "frequent ventricular premature beat": ["frequent", 'ventricular', 'prematur',
                                                                             'beat'],
                                     "endocrine condition": ['endocrin', 'condit'],
                                     "hypertensive nephrosclerosis": ['hypertens', 'nephrosclerosi'],
                                     "peripheral arterial occlusive disease": ['arteri', 'occlus'],
                                     "vestibular disorders": ['vestibular', 'disord'],
                                     "brain haemorrhage": ['brain', 'haemorrhag'],
                                     "dilated cardiomyopathy": ["dilat", "cardiomyopathi"],
                                     "prostat cancer": ["prostat", "cancer"]}


symptoms_to_background_diseases_bag_words = {"diabetes": ['diabet', "mellitus"],
                                             "cardiomyopathy": ['cardiomyopathi'],
                                             "atherosclerotic": ['atherosclerot']}

symptoms_to_background_diseases_sentences_bag = {"chronic obstructive pulmonary disease": ['obstruct', 'pulmonari'],
                                                 "coronary heart disease": ['ischem', 'heart'],
                                                 "chronic kidney disease": ['chronic', 'kidney', 'diseas']}

mexico_background_diseases_cols = [" diabetes,",
                                   " chronic obstructive pulmonary,",
                                    " asthma,",  " immunosuppression,",
                                    " hypertension,",
                                    " cardiovascular,",
                                    " obesity,",
                                    " kidney failure,"]

world_treatment_bag_words = {"home isolation": ["home", "quarantin"],
             "clinic": [],
             "hospitalized": ['hospit', "follow-up", 'intub', "fever"],
             }

world_treatment_sentences_bag = {"home isolation": ['not', 'hospit'],
                 "clinic": [],
                 "hospitalized": ['from', 'hospit', 'intens', 'care', 'under', 'treatment'],
                 }

severity_illness_dict = {"asymptomatic": ["Asymptomatic", "Asintomático"],
            "good": ["good", "Leve", 'Moderado', "Mild", "In progress", "In progress", "isolated"],
            "critical": ["critical", "Grave", "Severe", "Critical"],
            "deceased": ["deceased", 2, "Fallecido", "Died", "Deceased", "FATAL"],
            "cured": ["cured", 1, "Discharged", "Recovered", "Cured", "released",
                      "Clinically Recovered", "RESOLVED"],
            np.nan: [0, "Nan", "health", "Hospitalized", "Under Treatment", "To be provided",
                     "Pending admission", "Hospitalised"]}

world_severity_illness_bag_words = {"asymptomatic":['asymptomat'],
            "good": ["good", "stabl", "follow", 'mild', "follow-up", 'moder'],
            "critical": ["critic", "intens", "sever", 'unstabl'],
            "deceased": ["death", "dead", "die", "deceas", 'fatal' ],
            "cured": ["discharg", "releas", "cure", "recov", 'health', 'resolv'],
            "": ["isol", 'valid',  'treatment', "For validation"]}

world_severity_illness_sentences_bag = {"good": ['not', 'hospit', 'in', 'progress'],
                "critical": ['intens', 'care'],
                "deceased": [],
                "cured": ["discharged", "hospit"]}


severity_illness_from_symptoms_by_WHO = {"good": ["pneumonia", 'fever', 'cough', 'fatigue',
                                                  'discomfort', 'weakness', 'dizziness',
                                                  'rhinorrhoea', 'sneezing', 'sputum', 'headache',
                                                  'backache', 'diarrhea', 'chills', 'nausea',
                                                  'myalgia',
                     'anorexia','toothache','vomiting','gasp','influenza','sweating ','rigor',
                     'conjunctivitis','pharyngalgia','gastritis','influenza', 'nasal congestion',
                     'sore throat','muscular stiffness','myalgia','joint pain','esophageal reflux',
                     'abdominal pain','bone pain','eye irritation','dry mouth','dry throat',
                     'gastrointestinal bleeding','stuffy nose',"difficulty walking", "pleuritic chest pain"],
     "asymptomatic": ["no_symptom"],
    'critical': ["server" , "breathing difficulty", "dysphagia", "hypoxia", "septic",
                 "cardiac arrhythmia",'organ failure', 'respiratory failure',  'breathing difficulty'
    "sepsis", "hypertension", "azotemia", "pleural effusion","heart failure","kidney failure",
    "chest distress","acute coronary syndrome","cardiac arrhythmia",'septic shock',
    'cardiogenic shock','heart attack','electrolyte disorders','organ failure','primary myelofibrosis',
    'myocardial dysfunction','cardiac arrest','lesions on chest','respiratory failure',"respiratory infection",'primary myelofibrosis']}

